In [220]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import string
from nltk.corpus import stopwords

In [336]:
def text_process(text):
    """
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Returns a list of the cleaned text
    """
    # Check characters to see if they are in punctuation
    nopunc = [char for char in text if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Now just remove any stopwords
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [342]:
yelp = pd.read_csv('train.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [343]:
yelp.shape

(400001, 2)

In [344]:
yelp.describe()

label                                               text
count   400001                                             400000
unique       7                                             399958
top          2  I was at the opening day game. Let me just say...
freq    164201                                                  2

In [345]:
yelp.text.str.replace('[^a-zA-Z]', ' ')

0         Great mobile app with nice reward program  Mak...
1         Really fast and polite  Definitely recommend  ...
2         This place is always amazing  friendly staff a...
3         We did a Wine     class on a Friday night  Coo...
4         I am rounding up because I think this place ma...
5         My romantic tryst with the Planet Hollywood Po...
6         Just got color and a haircut  Finally after a ...
7         Never will go there again   Place was nearly e...
8         I ve come here for   years now  when it was NP...
9         Am            war ich mit   Kollegen mittags i...
10          stars  for take out   not recommended for di...
11        Nachdem wir jetzt das dritte Mal vor der T re ...
12        Hands down the best polish boy sandwich in Cle...
13        Oh Fuzzy s where to begin with you  Are any of...
14        I ve tried many a cupcakes  Magnolia  Prarie G...
15        If you put an Irish pub into a Walmart  this i...
16        Amazing Pho      I was almost 

In [367]:
str='this is a test'
for i in stop:
    str=str.replace(i,' ')
    print(str)

th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s a test
th s  s   test
th s  s   test
th s  s   test
th s  s   test
th s  s   test
th s  s   test
th s  s   

In [365]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [347]:
for i in stop:
    yelp.text.str.replace(i, ' ')
    print(i)

i
me
my
myself
we
our
ours
ourselves
you
you're
you've
you'll
you'd
your
yours
yourself
yourselves
he
him
his
himself
she
she's
her
hers
herself
it
it's
its
itself
they
them
their
theirs
themselves
what
which
who
whom
this
that
that'll
these
those
am
is
are
was
were
be
been
being
have
has
had
having
do
does
did
doing
a
an
the
and
but
if
or
because
as
until
while
of
at
by
for
with
about
against
between
into
through
during
before
after
above
below
to
from
up
down
in
out
on
off
over
under
again
further
then
once
here
there
when
where
why
how
all
any
both
each
few
more
most
other
some
such
no
nor
not
only
own
same
so
than
too
very
s
t
can
will
just
don
don't
should
should've
now
d
ll
m
o
re
ve
y
ain
aren
aren't
couldn
couldn't
didn
didn't
doesn
doesn't
hadn
hadn't
hasn
hasn't
haven
haven't
isn
isn't
ma
mightn
mightn't
mustn
mustn't
needn
needn't
shan
shan't
shouldn
shouldn't
wasn
wasn't
weren
weren't
won
won't
wouldn
wouldn't


In [351]:
yelp.head()

label                                               text
0     1  Great mobile app with nice reward program. Mak...
1     2  Really fast and polite. Definitely recommend. ...
2     2  This place is always amazing, friendly staff a...
3     1  We did a Wine 101 class on a Friday night. Coo...
4     1  I am rounding up because I think this place ma...

In [310]:
#yelp['text length'] = yelp['text'].apply(len)
yelp['text length']= yelp['text'].str.split().str.len()


In [413]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
porter_stemmer = PorterStemmer()
yelp['text']=yelp['text'].astype('object')

In [414]:
yelp['text']=yelp['text'].apply(lambda x : [porter_stemmer.stem(y) for y in x])

TypeError: 'float' object is not iterable

In [312]:
yelp_class = yelp[(yelp['label'] == 1) | (yelp['label'] == 0)|(yelp['label'] == 2) ]

In [313]:
#yelp_class.head

In [314]:
yelp['label'].unique()

array([1, 2, 0, '1', '2', '0',
       'My husband and I had not purchased a home before and we definitely needed some hand holding. They were patient and professional. We got our dream home and the entire experience was awesome! Thank you so much ladies for a job well done!'],
      dtype=object)

In [315]:
yelpchange=yelp
yelpchange = yelp[yelp.label !='My husband and I had not purchased a home before and we definitely needed some hand holding. They were patient and professional. We got our dream home and the entire experience was awesome! Thank you so much ladies for a job well done!']
yelpchange['label'].unique()

array([1, 2, 0, '1', '2', '0'], dtype=object)

In [316]:
yelpchange.label[yelpchange.label == '1'] = 1
yelpchange.label[yelpchange.label == '0']= 0
yelpchange.label[yelpchange.label == '2']= 2
yelpchange['label'].unique()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5984: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2910: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/anaconda3/li

array([1, 2, 0], dtype=object)

In [317]:
yelp.shape

(400001, 3)

In [318]:
yelpchange.shape

(400000, 3)

In [327]:
yelp_class= yelpchange[(yelpchange['label'] == 1) | (yelpchange['label'] == 0)|(yelpchange['label'] == 2) ]

In [393]:
X = yelp_class['text']
y = yelp_class['label']
y=y.astype('int64')
y.dtype

dtype('int64')

In [394]:
X.dtype

dtype('O')

<p> from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_transformer=TfidfVectorizer().fit(X)
X=tfidf_transformer.transform(X)</p>

In [395]:
from sklearn.feature_extraction.text import CountVectorizer

In [396]:
bow_transformer = CountVectorizer().fit(X)

In [397]:
print(len(bow_transformer.vocabulary_))

179154


In [398]:
X = bow_transformer.transform(X)

In [399]:
bow_transformer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [400]:
print('Shape of Sparse Matrix: ', X.shape)
print('Amount of Non-Zero occurences: ', X.nnz)

Shape of Sparse Matrix:  (400000, 179154)
Amount of Non-Zero occurences:  27749107


In [401]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

<h1> MultiClass Naive Bayes </h1>

In [402]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [403]:
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [404]:
preds = nb.predict(X_test)

In [405]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, preds))
print('\n')
print(classification_report(y_test, preds))

[[19021  4532   627]
 [ 2398 15217  2715]
 [ 4099  7603 63788]]


             precision    recall  f1-score   support

          0       0.75      0.79      0.77     24180
          1       0.56      0.75      0.64     20330
          2       0.95      0.84      0.89     75490

avg / total       0.84      0.82      0.83    120000



In [291]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, preds)

0.8171761354966686

<h1> Linear Regression </h1>


In [302]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [303]:
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)

KeyboardInterrupt: 

In [ ]:
print('Coefficients: \n', regr.coef_)
print('\n')
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print('Variance score: %.2f' % r2_score(y_test, y_pred))

<h1> Decision Tree </h1>


In [299]:
import pandas as pd
from sklearn import tree
from sklearn import metrics
import graphviz 
import sklearn
import matplotlib
import pydot
import seaborn as sns

from IPython.display import Image
from sklearn.externals.six import StringIO
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier

In [300]:
clf = tree.DecisionTreeClassifier(criterion='gini', splitter='best')
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [301]:
print(clf)
print('Accuracy = {}'.format(metrics.accuracy_score(y_pred, y_test)*100))
print('Confusion = {}'.format(metrics.confusion_matrix(y_pred, y_test)))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
Accuracy = 74.22943899089567
Confusion = [[10539  2406  2700]
 [ 2472  5717  4612]
 [ 2924  5153 42121]]
